dist: trusty

language: java
jdk:
  - openjdk8
  - oraclejdk8

script: ./gradlew build

notifications:
  email: false

# Exclude master because it is built on Jenkins
branches:
  except:
    - master
